#[project]
#name = "chronos"
#version = "1.2.0"
#requires-python = ">=3.8"
#license = { file = "LICENSE" }
#dependencies = [
#    "torch~=2.0",         # package was tested on 2.2
#    "transformers~=4.30",
#    "accelerate",
#]
#
#[project.optional-dependencies]
#debug = ["pytest~=8.0", "numpy~=1.21"]
#typecheck = ["mypy~=1.9"]
#training = ["gluonts[pro]", "numpy", "tensorboard", "typer", "typer-config", "joblib", "scikit-learn"]
#
#[tool.mypy]
#ignore_missing_imports = true
