training_data_paths:
 - "/home/elan/chronos/datasets/weatherbenchhourly.arrow"
 - "/home/elan/chronos/datasets/spanish_energy_weather.arrow"
 - "/home/elan/chronos/datasets/wikidaily.arrow"
 - "/home/elan/chronos/datasets/mexico_city_bikes.arrow"
 - "/home/elan/chronos/datasets/weatherbenchdaily.arrow"
 - "/home/elan/chronos/datasets/windfarmsdaily.arrow"
 - "/home/elan/chronos/datasets/weatherbenchweekly.arrow"
 - "/home/elan/chronos/datasets/solar5minutes.arrow"
 - "/home/elan/chronos/datasets/ushcnprcp.arrow"
 - "/home/elan/chronos/datasets/windfarmshourly.arrow"
 - "/home/elan/chronos/datasets/brazilian_cities_temperature.arrow"
 - "/home/elan/chronos/datasets/taxi.arrow"
 - "/home/elan/chronos/datasets/solar_hourly.arrow"
probability:
 - 0.076
 - 0.076
 - 0.076
 - 0.076
 - 0.076
 - 0.076
 - 0.076
 - 0.076
 - 0.076
 - 0.076
 - 0.076
 - 0.076
 - 0.076
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 10_000
save_steps: 1_000
log_steps: 1
per_device_train_batch_size: 32 #32
learning_rate: 0.0005
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 5_000
gradient_accumulation_steps: 1
model_id: google/t5-efficient-tiny
model_type: seq2seq
random_init: true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: false
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -100.0
  high_limit: 100.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 0
max_missing_prop: 0.9
use_eos_token: true