# This file loads all datasets contained in chronos/datasets (but do verify
# manually that no dataset is left behind.)
training_data_paths:
- "/home/elan/chronos/datasets/mydata500series.arrow"
- "/home/elan/chronos/datasets/spanish_energy_weather.arrow"
- "/home/elan/chronos/datasets/wikidaily.arrow"
- "/home/elan/chronos/datasets/mexico_city_bikes.arrow"
- "/home/elan/chronos/datasets/brazilian_cities_temperature.arrow"
- "/home/elan/chronos/datasets/taxi.arrow"
probability:
- 0.2
- 0.2
- 0.2
- 0.2
- 0.1
- 0.1
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 20
save_steps: 100_000
log_steps: 500
per_device_train_batch_size: 2 #32
learning_rate: 0.001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: google/t5-efficient-tiny
model_type: seq2seq
random_init: true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
